#!/usr/bin/env bash
# load rvm ruby

PROJECT=~/Projects/Procurement/
SCRAPER=scraper/
LOCKFILE=running.txt
SPIDER=procurementScrape/spiders/procurement_spider.py
OUTPUT=app/current

source /home/tigeorgia/.rvm/environments/ruby-1.9.2-p290

cd $PROJECT$SCRAPER
if [ ! -f $PROJECT$SCRAPER$LOCKFILE ]; then
	touch $PROJECT$SCRAPER$LOCKFILE
	python $PROJECT$SCRAPER$SPIDER FULL /var/data/procurement/app/current 
	cd $PROJECT$OUTPUT
	#rake procurement:full_scrape
	rm $PROJECT$SCRAPER$LOCKFILE
fi
	
