#!/usr/bin/env bash
# load rvm ruby

source /home/tigeorgia/.rvm/environments/ruby-1.9.2-p290

cd /var/data/procurement/scraper
if [ ! -f /var/data/procurement/scraper/running.txt ]; then
	touch /var/data/procurement/scraper/running.txt
	python /var/data/procurement/scraper/procurementScrape/spiders/procurement_spider.py FULL /var/data/procurement/app/current 
	cd /var/data/procurement/app/current
	rake procurement:full_scrape
	rm /var/data/procurement/scraper/running.txt
fi
	
